const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const PUBLIC=path.join(__dirname,'public');
if(!process.env.DATABASE_URL){console.error('DATABASE_URL is required');process.exit(1)}
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5});
const seedItems=["Coca-Cola","Coca-Cola Zero","Fanta Orange","Fanta Lemon","Sprite","Pepsi","Pepsi Max","7Up","Mirinda Orange","Schweppes Tonic","Schweppes Bitter Lemon","Schweppes Chapman","Maltina","Maltina Pineapple","Amstel Malta","Malta Guinness","Fayrouz Pineapple","Fayrouz Pear","Bigi Cola","Bigi Orange","Bigi Apple","Bigi Tropical","Bigi Chapman","Eva Water 50cl","Eva Water 75cl","Aquafina Water","Nestlé Pure Life Water","Cway Water","Heineken","Heineken 0.0","Goldberg","Trophy","Budweiser","Star Lager","Gulder","33 Export","Hero Lager","Life Lager","Harp","Desperados","Legend Extra Stout","Guinness Foreign Extra Stout","Guinness Smooth","Smirnoff Ice","Star Radler","Origin Beer","Origin Bitters","Hollandia Yoghurt","Hollandia Evaporated Milk","Hollandia Choco","Chivita 100% Orange","Chivita Active","Chivita Happy Hour","Five Alive","Pulpy Orange","Chi Exotic","Ribena","Lucozade Boost","Teem Bitter Lemon","Sosa Fruit Drink","Fearless Energy Drink","Predator Energy Drink","Monster Energy Drink","Red Bull","Power Horse","Bullet Energy Drink","Climax Energy Drink","Viju Milk","Viju Chocolate","Lacasera"];
const norm=s=>String(s||'').trim().replace(/\s+/g,' ').toLowerCase();
const num=n=>Math.max(0,Math.round(Number(n)||0));
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6){reject(Error('Request too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
async function seed(){const values=[],args=[];for(const name of seedItems){args.push(name,norm(name),'DRINK');values.push(`($${args.length-2},$${args.length-1},$${args.length})`)}await pool.query(`INSERT INTO products(name,normalized_name,category) VALUES ${values.join(',')} ON CONFLICT(normalized_name) DO NOTHING`,args)}
function mapItem(r){return{id:r.id,name:r.name,category:r.category}}
function mapShift(r,lines=[]){const payments={cash:Number(r.cash)||0,transfer:Number(r.transfer)||0,card:Number(r.card)||0};const clean=lines.map(l=>({id:l.id,itemId:l.product_id,name:l.product_name,category:l.category,sold:Number(l.sold)||0,amount:Number(l.amount)||0}));const grandTotal=clean.reduce((a,l)=>a+l.amount,0),paymentTotal=payments.cash+payments.transfer+payments.card;return{id:r.id,hotel:'E-Phoenix Hotels & Tourism',outlet:r.outlet,staff:r.staff_name,date:String(r.shift_date).slice(0,10),status:r.status,createdAt:r.created_at,updatedAt:r.updated_at,closedAt:r.closed_at,lines:clean,payments,grandTotal,paymentTotal,difference:paymentTotal-grandTotal}}
async function getShift(id,client=pool){const q=await client.query('SELECT * FROM shifts WHERE id=$1',[id]);if(!q.rowCount)return null;const l=await client.query('SELECT * FROM shift_lines WHERE shift_id=$1 ORDER BY created_at,id',[id]);return mapShift(q.rows[0],l.rows)}
async function allShifts(){const q=await pool.query('SELECT * FROM shifts ORDER BY updated_at DESC LIMIT 500');if(!q.rowCount)return[];const ids=q.rows.map(x=>x.id),l=await pool.query('SELECT * FROM shift_lines WHERE shift_id=ANY($1::uuid[]) ORDER BY created_at,id',[ids]);const by=new Map();for(const x of l.rows){if(!by.has(x.shift_id))by.set(x.shift_id,[]);by.get(x.shift_id).push(x)}return q.rows.map(r=>mapShift(r,by.get(r.id)||[]))}
function cleanLines(lines){const map=new Map();for(const raw of lines||[]){const name=String(raw.name||'').trim(),k=norm(name);if(!k)continue;const line={id:/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(raw.id||''))?raw.id:crypto.randomUUID(),itemId:raw.itemId||null,name,category:raw.category==='FOOD'?'FOOD':'DRINK',sold:Math.max(0,Math.floor(Number(raw.sold)||0)),amount:num(raw.amount)};if(map.has(k)){const x=map.get(k);x.sold+=line.sold;x.amount+=line.amount}else map.set(k,line)}return[...map.values()]}
function serveFile(req,res){let p=req.url==='/'?'/index.html':req.url.split('?')[0];try{p=decodeURIComponent(p)}catch{}const f=path.resolve(PUBLIC,'.'+p);if(!f.startsWith(PUBLIC+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found')}const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8'};res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream','Cache-Control':'no-cache'});fs.createReadStream(f).pipe(res)}
const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://localhost'),pathname=url.pathname;
 if(pathname==='/api/health'&&req.method==='GET'){await pool.query('SELECT 1');return json(res,200,{ok:true,database:'connected'})}
 if(pathname==='/api/bootstrap'&&req.method==='GET'){await seed();const [items,shifts]=await Promise.all([pool.query('SELECT id,name,category FROM products WHERE active=true ORDER BY category,name'),allShifts()]);return json(res,200,{items:items.rows.map(mapItem),shifts})}
 if(pathname==='/api/shifts/start'&&req.method==='POST'){const b=await body(req),staff=String(b.staff||'').trim(),date=b.date||new Date().toISOString().slice(0,10),outlet=String(b.outlet||'Pool Bar').trim();if(!staff)return json(res,400,{error:'Staff name required'});let q=await pool.query("SELECT id FROM shifts WHERE status='OPEN' AND normalized_staff_name=$1 AND shift_date=$2 AND outlet=$3 LIMIT 1",[norm(staff),date,outlet]);if(q.rowCount)return json(res,200,await getShift(q.rows[0].id));try{q=await pool.query("INSERT INTO shifts(staff_name,normalized_staff_name,outlet,shift_date,status) VALUES($1,$2,$3,$4,'OPEN') RETURNING id",[staff,norm(staff),outlet,date]);return json(res,201,await getShift(q.rows[0].id))}catch(e){if(e.code==='23505'){q=await pool.query("SELECT id FROM shifts WHERE status='OPEN' AND normalized_staff_name=$1 AND shift_date=$2 AND outlet=$3 LIMIT 1",[norm(staff),date,outlet]);if(q.rowCount)return json(res,200,await getShift(q.rows[0].id))}throw e}}
 const m=pathname.match(/^\/api\/shifts\/([0-9a-f-]+)(\/close)?$/i);
 if(m&&!m[2]&&req.method==='PUT'){const b=await body(req),client=await pool.connect();try{await client.query('BEGIN');const q=await client.query("SELECT status FROM shifts WHERE id=$1 FOR UPDATE",[m[1]]);if(!q.rowCount){await client.query('ROLLBACK');return json(res,404,{error:'Shift not found'})}if(q.rows[0].status==='CLOSED'){await client.query('ROLLBACK');return json(res,409,{error:'Closed shifts cannot be edited'})}const p=b.payments||{};await client.query('UPDATE shifts SET cash=$2,transfer=$3,card=$4,updated_at=now() WHERE id=$1',[m[1],num(p.cash),num(p.transfer),num(p.card)]);await client.query('DELETE FROM shift_lines WHERE shift_id=$1',[m[1]]);for(const l of cleanLines(b.lines)){let productId=l.itemId;if(productId){const valid=await client.query('SELECT id FROM products WHERE id=$1',[productId]);if(!valid.rowCount)productId=null}await client.query('INSERT INTO shift_lines(id,shift_id,product_id,product_name,normalized_name,category,sold,amount) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[l.id,m[1],productId,l.name,norm(l.name),l.category,l.sold,l.amount])}await client.query('COMMIT');return json(res,200,await getShift(m[1]))}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
 if(m&&m[2]==='/close'&&req.method==='POST'){const q=await pool.query("UPDATE shifts SET status='CLOSED',closed_at=now(),updated_at=now() WHERE id=$1 AND status='OPEN' RETURNING id",[m[1]]);if(!q.rowCount){const existing=await getShift(m[1]);if(!existing)return json(res,404,{error:'Shift not found'});return json(res,200,existing)}return json(res,200,await getShift(m[1]))}
 if(pathname==='/api/items'&&req.method==='POST'){const b=await body(req),name=String(b.name||'').trim(),category=b.category==='FOOD'?'FOOD':'DRINK';if(!name)return json(res,400,{error:'Product name required'});const q=await pool.query("INSERT INTO products(name,normalized_name,category) VALUES($1,$2,$3) ON CONFLICT(normalized_name) DO UPDATE SET category=EXCLUDED.category,active=true,updated_at=now() RETURNING id,name,category",[name,norm(name),category]);return json(res,200,mapItem(q.rows[0]))}
 return serveFile(req,res);
}catch(e){console.error(e);return json(res,500,{error:'Server error'})}});
const port=Number(process.env.PORT||3000);server.listen(port,()=>console.log(`E-Phoenix Shift Sales running on port ${port}`));
